### ISSUE TITLE
Bug in SeerUtils.zipFiles

### ISSUE THREAD

**Issue by schadega** [imsweb/seerutils#1]
In SeerUtils.zipFiles, I think there's a bug in the line:  

`internalZip(file, zipOutput, to.getParentFile().getAbsolutePath().length() - 1);`

I think the “to” should be “file". This line calculates the length of the file path and submits that as a parameter in SeerUtils.internalZip. The length is needed to replace characters in the file path, but the length that's calculated is for "to" while the file path that's changed is for “file”.

**Comment by depryf** [comment]
@schadega you seem to know exactly what needs to be fixed. Can you please submit a merge request with the fix (don't forget to add an entry to the changelog file). Thanks!
